import glob
env = Environment(CCFLAGS=['-pthread','-Wall'])

commonSources = glob.glob("common/*.c");
sources = glob.glob("core/**.c") + commonSources;
env.Program(target="build/server",source=sources,LIBS=['pthread'])
#env.Program(target="build/testClient",source=["testClient.c", "common/common.c", "common/slog.c"])
