env = Environment(CCFLAGS=['-pthread','-Wall'])

env.Program(target="server",source=["server.c","common.c","slog.c","nick_val.c"],LIBS=['pthread'])
env.Program(terget="testClient",source=["testClient.c", "common.c", "slog.c"])
