env = Environment(CCFLAGS=['-pthread','-Wall'])

env.Program(target="build/server",source=["core/server.c","common/common.c","common/slog.c","common/nick_val.c"],LIBS=['pthread'])
env.Program(terget="build/testClient",source=["testClient.c", "common/common.c", "common/slog.c"])
