#ifndef __SENET_ERROR_H
#define __SENET_ERROR_H

typedef enum {
	GENERAL_ERR = -1,
	ERR_MSG = 1,
	ERR_MSG_TYPE,
	ERR_MSG_CONTENT,
	ERR_NICK_TOO_SHORT,
	ERR_NICK_TOO_LONG,
    ERR_FIRST_CHAR_INV,
    ERR_CONTAINS_INV_CHAR,
	ERR_NICK_EXISTS,
	ERR_TURN
} senetError;

#endif
